/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lambung;

import static Lambung.Home.gastritis;
import static Lambung.Home.dispepsia;
import static Lambung.Home.gerd;
import static Lambung.Home.totalGastritis;
import static Lambung.Home.totalDispepsia;
import static Lambung.Home.totalGERD;
import java.awt.Image;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import javax.swing.ImageIcon;
/**
 *
 * @author ariarf
 */
public class Diagnosa extends javax.swing.JFrame {
    String pasien;
    String penyakit;
    String penanganan;
    String pesanPenyakit = "Dear %s.\nBerdasarkan perhitungan sistem kami, anda terdiagnosa penyakit %s \ndengan hasil persentase tertinggi sebesar %.2f%s.";
    String pesanPenanganan = "Adapun saran penanganan berdasarkan penyakit dari hasil diagnosa sebelumnya\nyaitu : %s.";

    /**
     * Creates new form Diagnosa
     */
    public Diagnosa() {
        initComponents();
        Image icon = new ImageIcon(this.getClass().getResource("Jframe Icon.png")).getImage();
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        r11 = new javax.swing.JRadioButton();
        r12 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        r21 = new javax.swing.JRadioButton();
        r22 = new javax.swing.JRadioButton();
        r31 = new javax.swing.JRadioButton();
        r32 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        r41 = new javax.swing.JRadioButton();
        r42 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        r51 = new javax.swing.JRadioButton();
        r52 = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        r61 = new javax.swing.JRadioButton();
        r62 = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        r72 = new javax.swing.JRadioButton();
        r71 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        r82 = new javax.swing.JRadioButton();
        r81 = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        r91 = new javax.swing.JRadioButton();
        r92 = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        r101 = new javax.swing.JRadioButton();
        r102 = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        r111 = new javax.swing.JRadioButton();
        r112 = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Data Diri");

        jRadioButton9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton9.setText("Ya");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });

        jRadioButton10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton10.setText("Tidak");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Apakah anda mengalami perut kembung?");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SP - Sipaling Pakar - Diagnosa");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Nama");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Jenis Kelamin");

        buttonGroup1.add(r11);
        r11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        r11.setText("Laki- Laki");

        buttonGroup1.add(r12);
        r12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        r12.setText("Peremuan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(r11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(r12)))
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r11)
                            .addComponent(r12))
                        .addGap(5, 5, 5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Apakah anda mengalami nyeri perut?");

        buttonGroup2.add(r21);
        r21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        r21.setText("Ya");
        r21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r21ActionPerformed(evt);
            }
        });

        buttonGroup2.add(r22);
        r22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        r22.setText("Tidak");

        buttonGroup3.add(r31);
        r31.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        r31.setText("Ya");
        r31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r31ActionPerformed(evt);
            }
        });

        buttonGroup3.add(r32);
        r32.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        r32.setText("Tidak");
        r32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r32ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("Apakah anda mengalami mual dan muntah?");

        buttonGroup4.add(r41);
        r41.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        r41.setText("Ya");
        r41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r41ActionPerformed(evt);
            }
        });

        buttonGroup4.add(r42);
        r42.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        r42.setText("Tidak");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("Apakah anda mengalami perut kembung?");

        buttonGroup5.add(r51);
        r51.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        r51.setText("Ya");
        r51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r51ActionPerformed(evt);
            }
        });

        buttonGroup5.add(r52);
        r52.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        r52.setText("Tidak");

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("Apakah anda mengalami nafsu makan berkurang?");

        buttonGroup6.add(r61);
        r61.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        r61.setText("Ya");
        r61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r61ActionPerformed(evt);
            }
        });

        buttonGroup6.add(r62);
        r62.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        r62.setText("Tidak");

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Apakah anda mengalami tinja berwarna hitam?");

        buttonGroup7.add(r72);
        r72.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        r72.setText("Tidak");

        buttonGroup7.add(r71);
        r71.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        r71.setText("Ya");
        r71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r71ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setText("Apakah anda mengalami perut terasa penuh?");

        buttonGroup8.add(r82);
        r82.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        r82.setText("Tidak");

        buttonGroup8.add(r81);
        r81.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        r81.setText("Ya");
        r81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r81ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setText("Apakah anda mengalami sering bersendawa?");

        buttonGroup9.add(r91);
        r91.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        r91.setText("Ya");
        r91.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r91ActionPerformed(evt);
            }
        });

        buttonGroup9.add(r92);
        r92.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        r92.setText("Tidak");

        jLabel23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel23.setText("Apakah anda mengalami keluar cairan dari lambur?");

        buttonGroup10.add(r101);
        r101.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        r101.setText("Ya");
        r101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r101ActionPerformed(evt);
            }
        });

        buttonGroup10.add(r102);
        r102.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        r102.setText("Tidak");

        jLabel24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel24.setText("Apakah anda mengalami dehidrasi?");

        buttonGroup11.add(r111);
        r111.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        r111.setText("Ya");
        r111.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r111ActionPerformed(evt);
            }
        });

        buttonGroup11.add(r112);
        r112.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        r112.setText("Tidak");

        jLabel25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel25.setText("Apakah anda mengalami demam?");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(r81)
                        .addGap(36, 36, 36)
                        .addComponent(r82))
                    .addComponent(jLabel11)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(r21)
                        .addGap(36, 36, 36)
                        .addComponent(r22))
                    .addComponent(jLabel17)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(r31)
                        .addGap(36, 36, 36)
                        .addComponent(r32))
                    .addComponent(jLabel18)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(r41)
                        .addGap(36, 36, 36)
                        .addComponent(r42))
                    .addComponent(jLabel19)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(r51)
                        .addGap(36, 36, 36)
                        .addComponent(r52))
                    .addComponent(jLabel20)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(r61)
                        .addGap(36, 36, 36)
                        .addComponent(r62))
                    .addComponent(jLabel21)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(r71)
                        .addGap(36, 36, 36)
                        .addComponent(r72))
                    .addComponent(jLabel23)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(r91)
                        .addGap(36, 36, 36)
                        .addComponent(r92))
                    .addComponent(jLabel24)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(r101)
                        .addGap(36, 36, 36)
                        .addComponent(r102))
                    .addComponent(jLabel25)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(r111)
                        .addGap(36, 36, 36)
                        .addComponent(r112)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r21)
                    .addComponent(r22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r31)
                    .addComponent(r32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r41)
                    .addComponent(r42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r51)
                    .addComponent(r52))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r61)
                    .addComponent(r62))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r71)
                    .addComponent(r72))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r81)
                    .addComponent(r82))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r91)
                    .addComponent(r92))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r101)
                    .addComponent(r102))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r111)
                    .addComponent(r112))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnSimpan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(btnSimpan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSimpan)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    // Fungsi untuk menghitung nilai CF penyakit dari gejala yang dirasakan pasien
    public static Double hitungCF(
        // totalGejalaPenyakitX -> Total gejala pasien pada penyakit x
        // gejalaPenyakitX -> List gejala penyakit x
        // gejalaPenyakitXPasien -> List gejala yang dirasakan pasien pada penyakit x
        int totalGejalaPasienPenyakitX, 
        Map<String, Double[]> gejalaPenyakitX,
        ArrayList<String> gejalaPenyakitXPasien) {
        
        // Variabel yang digunakan dalam perhitungan CF Penyakit
        ArrayList<Double[]> cfGabungan = new ArrayList<Double[]>();
        Double cfGejala1 = 0.0, cfGejala2 = 0.0, cfGejalaSelanjutnya = 0.0;
        Double cfAkhirPenyakitX = 0.0;
        
        // Pengkondisian untuk menghitung nilai CF berdasarkan total gejala yang dirasakan pasien
        if(totalGejalaPasienPenyakitX == 1) {
            cfGabungan.add(gejalaPenyakitX.get(gejalaPenyakitXPasien.get(0)));
            cfAkhirPenyakitX = cfGabungan.get(0)[0] * cfGabungan.get(0)[1];
            cfAkhirPenyakitX *= 100;
        } else if (totalGejalaPasienPenyakitX > 1) {
            cfGabungan.add(gejalaPenyakitX.get(gejalaPenyakitXPasien.get(0)));
            cfGabungan.add(gejalaPenyakitX.get(gejalaPenyakitXPasien.get(1)));
            cfGejala1 = cfGabungan.get(0)[0] * cfGabungan.get(0)[1];
            cfGejala2 = cfGabungan.get(1)[0] * cfGabungan.get(1)[1];
            cfAkhirPenyakitX = cfGejala1 + cfGejala2 * (1 - cfGejala1);
            for (int i = 2; i < gejalaPenyakitXPasien.size(); i++) {
                cfGabungan.add(gejalaPenyakitX.get(gejalaPenyakitXPasien.get(i)));
                cfGejalaSelanjutnya = cfGabungan.get(i)[0] * cfGabungan.get(i)[1];
                cfAkhirPenyakitX = cfAkhirPenyakitX + cfGejalaSelanjutnya * (1 - cfAkhirPenyakitX);
            } 
            cfAkhirPenyakitX *= 100;
        }
        return cfAkhirPenyakitX;
    }
    
    private void clearForm() {
        inputNama.setText("");
        r11.setSelected(false);
        r12.setSelected(false);
        r21.setSelected(false);
        r22.setSelected(false);
        r31.setSelected(false);
        r32.setSelected(false);
        r41.setSelected(false);
        r42.setSelected(false);
        r51.setSelected(false);
        r52.setSelected(false);
        r61.setSelected(false);
        r62.setSelected(false);
        r71.setSelected(false);
        r72.setSelected(false);
        r81.setSelected(false);
        r82.setSelected(false);
        r91.setSelected(false);
        r92.setSelected(false);
        r101.setSelected(false);
        r102.setSelected(false);
        r111.setSelected(false);
        r112.setSelected(false);
    }
    
//    private void setHasil(String penyakit, String pasien, String penanganan, String persentase) {
//        Hasil.txtPenyakit.setText(String.format(txtHasilPenyakit, pasien, penyakit, persentase));
//        Hasil.txtPenanganan.setText(String.format(txtHasilPenanganan, penanganan));
//    }
    
    private void r21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r21ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void r31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r31ActionPerformed

    private void r41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r41ActionPerformed

    private void r51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r51ActionPerformed

    private void r61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r61ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r61ActionPerformed

    private void r71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r71ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r71ActionPerformed

    private void r81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r81ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r81ActionPerformed

    private void r91ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r91ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r91ActionPerformed

    private void r101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r101ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r101ActionPerformed

    private void r111ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r111ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r111ActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        pasien = inputNama.getText();
        Hasil tabHasil;
        
         // List gejala penyakit lambung (Umum)
        String[][] listGejala = {
            {"G01", "Nyeri perut"}, 
            {"G02", "Mual muntah"}, 
            {"G03", "Perut kembung"},
            {"G04", "Nafsu makan berkurang"},
            {"G05", "Tinja berwarna hitam"},
            {"G06", "Perut terasa penuh"},
            {"G07", "Sering bersendawa"},
            {"G08", "Keluar cairan dari lambung"},
            {"G09", "Dehidrasi"},
            {"G10", "Demam"}
        };
        
        // Gejala penyakit gastritis (Spesifik) 
        Map<String, Double[]> gejalaGastritis  = new HashMap<String, Double[]>();
        gejalaGastritis.put("G01", new Double[] {0.7,0.8});
        gejalaGastritis.put("G02", new Double[] {0.5,0.6});
        gejalaGastritis.put("G03", new Double[] {0.5,0.6});
        gejalaGastritis.put("G04", new Double[] {0.7,0.8});
        gejalaGastritis.put("G05", new Double[] {0.3,0.8});
        
        // Gejala penyakit dispepsia (Spesifik)
        Map<String, Double[]> gejalaDispepsia  = new HashMap<String, Double[]>();
        gejalaDispepsia.put("G02", new Double[] {0.7,0.8});
        gejalaDispepsia.put("G03", new Double[] {0.4,0.6});
        gejalaDispepsia.put("G04", new Double[] {0.6,0.8});
        gejalaDispepsia.put("G06", new Double[] {0.5,0.6});
        gejalaDispepsia.put("G07", new Double[] {0.5,0.6});
        gejalaDispepsia.put("G08", new Double[] {0.4,0.6});
        
        // Gejala penyakit gerd (Spesifik 
        Map<String, Double[]> gejalaGerd  = new HashMap<String, Double[]>();
        gejalaGerd.put("G03", new Double[] {0.5,0.6});
        gejalaGerd.put("G09", new Double[] {0.5,0.6});
        gejalaGerd.put("G10", new Double[] {0.7,0.8});
        
        // List gejala pasien 
        ArrayList<String> listGejalaPasien = new ArrayList<String>();
        
        // Mencatat gejala yang dirasakan oleh pasien.
        if(r21.isSelected()) {
            listGejalaPasien.add("G01");
        }
        if(r31.isSelected()) {
            listGejalaPasien.add("G02");
        }
        if(r41.isSelected()) {
            listGejalaPasien.add("G03");
        }
        if(r51.isSelected()) {
            listGejalaPasien.add("G04");
        }
        if(r61.isSelected()) {
            listGejalaPasien.add("G05");
        }
        if(r71.isSelected()) {
            listGejalaPasien.add("G06");
        }
        if(r81.isSelected()) {
            listGejalaPasien.add("G07");
        }
        if(r91.isSelected()) {
            listGejalaPasien.add("G08");
        }
        if(r101.isSelected()) {
            listGejalaPasien.add("G09");
        }
        if(r111.isSelected()) {
            listGejalaPasien.add("G10");
        }
        
        // Hitung banyaknya gejala yang dimiliki user yang dibandingkan dengan gejala yang dimiliki
        // oleh masing-masing penyakit dan mencatat gejalanya
        int totalGejalaPasienPenyakitGastritis = 0, 
            totalGejalaPasienPenyakitDispepsia = 0, 
            totalGejalaPasienPenyakitGerd = 0;
        
        Set<String> gastritisKeys = gejalaGastritis.keySet();
        Set<String> dispepsiaKeys = gejalaDispepsia.keySet();
        Set<String> gerdKeys = gejalaGerd.keySet();
        
        ArrayList<String> gejalaPasienPenyakitGastritis = new ArrayList<String>();
        ArrayList<String> gejalaPasienPenyakitDispepsia = new ArrayList<String>();
        ArrayList<String> gejalaPasienPenyakitGerd = new ArrayList<String>();
        
        for(String gejalaPasien : listGejalaPasien) {
            if(gastritisKeys.contains(gejalaPasien)) {
                totalGejalaPasienPenyakitGastritis += 1;
                gejalaPasienPenyakitGastritis.add(gejalaPasien);
            }
            if(dispepsiaKeys.contains(gejalaPasien)) {
                totalGejalaPasienPenyakitDispepsia += 1;
                gejalaPasienPenyakitDispepsia.add(gejalaPasien);
            }
            if(gerdKeys.contains(gejalaPasien)) {
                totalGejalaPasienPenyakitGerd += 1;
                gejalaPasienPenyakitGerd.add(gejalaPasien);
            }
        }
        
        // Menampilkan hasil input gejala yang dirasakan oleh pasien dan menampilkan total gejala pada masing-masing penyakit
        // berdasarkan hasil input gejala pasien
        System.out.println("*Gejala*");
        System.out.println("Gejala yang dirasakan pasien    : " + listGejalaPasien);
        System.out.println("Total Gejala Penyakit Gastritis : " + totalGejalaPasienPenyakitGastritis + " - " + gejalaPasienPenyakitGastritis);
        System.out.println("Total Gejala Penyakit Dispepsia : " + totalGejalaPasienPenyakitDispepsia + " - " + gejalaPasienPenyakitDispepsia);
        System.out.println("Total Gejala Penyakit GERD      : " + totalGejalaPasienPenyakitGerd + " - " + gejalaPasienPenyakitGerd);
        System.out.println("");
        
        // Hitung penyakit CF penyakit gastritis, dispepsia, dan gerd
        Double cfPenyakitGastritis = hitungCF(totalGejalaPasienPenyakitGastritis, gejalaGastritis, gejalaPasienPenyakitGastritis);
        Double cfPenyakitDispepsia = hitungCF(totalGejalaPasienPenyakitDispepsia, gejalaDispepsia, gejalaPasienPenyakitDispepsia);
        Double cfPenyakitGerd = hitungCF(totalGejalaPasienPenyakitGerd, gejalaGerd, gejalaPasienPenyakitGerd);
        
        // Menampilkan hasil perhitungan CF penyakit gastritis
        System.out.println("*Certainty Factor (CF)*");
        System.out.printf("CF Penyakit Gastritis: %.2f%s\n", cfPenyakitGastritis, "%");
        
        // Menampilkan hasil perhitungan CF penyakit dispepsia
        System.out.printf("CF Penyakit Dispepsia: %.2f%s\n", cfPenyakitDispepsia, "%");
        
        // Menampilkan hasil perhitungan CF penyakit gerd
        System.out.printf("CF Penyakit GERD     : %.2f%s", cfPenyakitGerd, "%");
        System.out.println("\n");
        
        // Kesimpulan
        NumberFormat formater = new DecimalFormat("#00.00");
        if (cfPenyakitGastritis >= cfPenyakitDispepsia && cfPenyakitGastritis >= cfPenyakitGerd) {
            penyakit = "Gastritis";
            penanganan = "\n\n1. Minum Promag\n" +
                         "2. Jangan telat makan\n" +
                         "3. Hindari makan pedas, asam dan keras\n" +
                         "4. Pemberian gastrolan, propepsa sirup, vometa, dan mertiga\n" +
                         "5. Mengganti kebiasaan makanan";
            gastritis += 1;
            totalGastritis.setText(gastritis.toString());
            dispose();
            tabHasil = new Hasil(String.format(pesanPenyakit, pasien, penyakit, cfPenyakitGastritis, "%"), 
                                 String.format(pesanPenanganan, penanganan));
            System.out.println(String.format(pesanPenyakit, pasien, penyakit, cfPenyakitGastritis, "%"));
            System.out.println(String.format(pesanPenanganan, penanganan));
            tabHasil.show();
        } else if (cfPenyakitDispepsia >= cfPenyakitGastritis && cfPenyakitDispepsia >= cfPenyakitGerd) {
            penyakit = "Dispepsia";
            penanganan = "\n\n1.Jika karena berat badan maka mengganti pola makan seimbang\n" +
                         "2. Stress melakukan olahraga, meditasi\n" +
                         "3. Pemberian antacid";
            dispepsia += 1;
            totalDispepsia.setText(dispepsia.toString());
            dispose();
            tabHasil = new Hasil(String.format(pesanPenyakit, pasien, penyakit, cfPenyakitDispepsia, "%"), 
                                 String.format(pesanPenanganan, penanganan));
            System.out.println(String.format(pesanPenyakit, pasien, penyakit, cfPenyakitDispepsia, "%"));
            System.out.println(String.format(pesanPenanganan, penanganan));
            tabHasil.show();
            
        } else if (cfPenyakitGerd >= cfPenyakitGastritis && cfPenyakitGerd >= cfPenyakitDispepsia) {
            penyakit = "GERD";
            penanganan = "\n\n1. GERD ringan memakan makanan sehat yang rendah lemak, dan pemberian\nobat penghambat pompa proton\n" +
                         "2. GERD parah penanganannya dengan operasi\n" +
                         "3. Merubah pola hidup menjadi lebih sehat, berhenti merokok, hindari berbaring\n setelah makan ";
            gerd += 1;
            totalGERD.setText(gerd.toString());
            dispose();
            tabHasil = new Hasil(String.format(pesanPenyakit, pasien, penyakit, cfPenyakitGerd, "%"), 
                                 String.format(pesanPenanganan, penanganan));
            System.out.println(String.format(pesanPenyakit, pasien, penyakit, cfPenyakitGerd, "%"));
            System.out.println(String.format(pesanPenanganan, penanganan));
            tabHasil.show();
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void r32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r32ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diagnosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diagnosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diagnosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diagnosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diagnosa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JTextField inputNama;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JRadioButton r101;
    private javax.swing.JRadioButton r102;
    private javax.swing.JRadioButton r11;
    private javax.swing.JRadioButton r111;
    private javax.swing.JRadioButton r112;
    private javax.swing.JRadioButton r12;
    private javax.swing.JRadioButton r21;
    private javax.swing.JRadioButton r22;
    private javax.swing.JRadioButton r31;
    private javax.swing.JRadioButton r32;
    private javax.swing.JRadioButton r41;
    private javax.swing.JRadioButton r42;
    private javax.swing.JRadioButton r51;
    private javax.swing.JRadioButton r52;
    private javax.swing.JRadioButton r61;
    private javax.swing.JRadioButton r62;
    private javax.swing.JRadioButton r71;
    private javax.swing.JRadioButton r72;
    private javax.swing.JRadioButton r81;
    private javax.swing.JRadioButton r82;
    private javax.swing.JRadioButton r91;
    private javax.swing.JRadioButton r92;
    // End of variables declaration//GEN-END:variables
}
